version: '3.4'

services:
  weatherportal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  weatherapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"

