version: '3.4'

services:
  weatherportal:
    image: "adnancontregistry.azurecr.io/weatherportal:latest"
    build:
      context: .
      dockerfile: WeatherPortal/Dockerfile
  weatherapi:
    image: "adnancontregistry.azurecr.io/weatherapi:latest"
    build:
      context: .
      dockerfile: WeatherAPI/Dockerfile

